from rest_framework import routers

#
# This module configures the URL routing for the API endpoints in the polls application.
# Imports:
#     routers (rest_framework.routers): Provides a way to automatically determine the URL conf for the API.
#     QuestionViewSet (polls.api_views): The view set for handling Question model operations.
# Variables:
#     router (DefaultRouter): An instance of DefaultRouter to handle URL routing.
#     urlpatterns (list): The list of URL patterns generated by the router.
# Functionality:
#     - Registers the QuestionViewSet with the router under the 'questions' URL prefix.
#     - Exposes the generated URL patterns through the urlpatterns variable.
#

from .api_views import QuestionViewSet, ChoiceViewSet

router = routers.DefaultRouter()
router.register(r'questions', QuestionViewSet)
router.register(r'choices', ChoiceViewSet)

urlpatterns = router.urls
